licenses(["notice"])

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "engine",
    srcs = ["engine.cpp"],
    hdrs = ["engine.h"],
)

cc_library(
    name = "window",
    hdrs = ["window.h"],
    srcs = ["window.cpp"],
)
